name = "backend"
main = "src/index.js"
compatibility_date = "2024-10-19"
compatibility_flags = [ "nodejs_compat" ]


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNzMwOGU5MzYtOGY1MC00YWIxLWJhZTgtNGIxMWRiOGY2ODVjIiwidGVuYW50X2lkIjoiNTYxMjQxNWIxNGNjZTY5N2Y1YTA3N2JmOWEyN2UwNDU3M2EzNGQ0NmYyMmUxNWIwODIzMDkyNmI4YTgyYjAwNiIsImludGVybmFsX3NlY3JldCI6IjQ2MzQ4YzRlLTBlNDAtNDZiMi1iYjkxLTk5OGY2ODU1MGZiMSJ9.XlldHEmhXvHdh_YvwRYIJ--uwTZi9BCbKBcg4HUJcp8"
GEMINI_API_KEY='AIzaSyDoxjl6fZTANxImZbZq9sLmGAsB3Vre748'
JWT_SECRET='my_secret_key'